<?xml version="1.0"?>

<robot name="mobileRoboticArm" xmlns:xacro="http://ros.org/wiki/xacro">

	<!--Materials Start-->
	<material name="black">
		<color rgba="0.0 0.0 0.0 1.0"/>
	</material>

	<material name="white">
		<color rgba="1.0 1.0 1.0 1.0"/>
	</material>

	<material name="red">
		<color rgba="0.8 0.0 0.0 1.0"/>
	</material>

	<material name="blue">
		<color rgba="0.0 0.0 0.8 1.0"/>
	</material>

	<material name="green">
		<color rgba="0.0 0.8 0.0 1.0"/>
	</material>

	<material name="grey">
		<color rgba="0.5 0.5 0.5 1.0"/>
	</material>

	<material name="orange">
		<color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
	</material>

	<material name="brown">
		<color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
	</material>
	<!--Materials End-->

	<xacro:property name="base_height" value="0.2" /> <!--x direction -->
	<xacro:property name="base_width" value="0.2" /> <!--y direction -->
	<xacro:property name="base_depth" value="0.20" /> <!--z direction -->
	<xacro:property name="base_mass" value="1.488" /> <!--base mass -->

	<xacro:property name="ball_wheel_radius" value="0.005" /> <!--base wheel radius -->
	<xacro:property name="wheel_radius" value="0.06" /> <!--wheel radius -->
	<xacro:property name="wheel_thickness" value="0.03" /> <!--wheel thickness -->	
	<xacro:property name="wheel_mass" value="0.240" /> <!--wheel mass-->

	<xacro:property name="arm_height" value="0.06" /> <!--x direction -->
	<xacro:property name="arm_width" value="0.06" /> <!--y direction -->
	<xacro:property name="arm_depth" value="0.10" /> <!--z direction -->
	<xacro:property name="arm_mass" value="0.168" /> <!--arm mass -->

	<!--MACROS START-->

	<!--Inertial Macro-->
	<xacro:macro name="default_inertial" params="mass ixx:=1 ixy:=0 ixz:=0 iyy:=1 iyz:=0 izz:=1">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}" iyy="${iyy}" iyz="${iyz}" izz="${izz}"/>
		</inertial>
	</xacro:macro>
	<!--Inertial Macro-->

	<!--Arm Link Macro-->
	<xacro:macro name="arm_link" params="suffix parent reflect height color mesh_path mass joint_type lower_limit upper_limit axis_x axis_y axis_z ixx:=1 ixy:=0 ixz:=0 iyy:=1 iyz:=0 izz:=1 arm_width_ arm_height_ arm_depth_ motor=0 jointInterface=Position ">
		<link name="armLink${suffix}">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<!--mesh filename="package://innomech/meshes/linked_mx_64t.stl" scale="0.01 0.01 0.01"/-->
					<mesh filename="${mesh_path}" scale="0.01 0.01 0.01"/>
				</geometry>
				<material name="${color}"/>
			</visual>

			<collision>
				<origin xyz="0 0 ${(1-motor)*arm_depth_}" rpy="0 0 0"/>
				<geometry>
					<box size="${arm_width_} ${arm_height_} ${arm_depth_}" />
				</geometry>
			</collision>
			<xacro:default_inertial mass="${mass}" ixx="${ixx}"  ixy="${ixy}" ixz="${ixz}" iyy="${iyy}" iyz="${iyz}" izz="${izz}"/>
		</link>	

		<!-- Joint-->
		<joint name="${parent}_armLink${suffix}_joint" type="${joint_type}">
			<parent link="${parent}"/>
			<child link="armLink${suffix}"/>
			<origin xyz="0 0 ${height}" rpy="0 0 0"/>
			<axis xyz="${axis_x} ${axis_y} ${axis_z}"/>
			<limit velocity="4.8" effort="1" lower="${lower_limit}" upper="${upper_limit}" />
		</joint>

		<transmission name="armLink${suffix}_transmission" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="armLink${suffix}_motor">
				
				<hardwareInterface>hardware_interface/${jointInterface}JointInterface</hardwareInterface>
			</actuator>
			<joint name="${parent}_armLink${suffix}_joint">
				<hardwareInterface>hardware_interface/${jointInterface}JointInterface</hardwareInterface>
			</joint>
		</transmission>
	</xacro:macro>
	<!--Arm Link Macro-->

	<!--Wheel Macro-->
	<xacro:macro name="wheel_link" params="suffix parent reflect height color mesh_path mass joint_type:=continuous ixx:=1 ixy:=0 ixz:=0 iyy:=1 iyz:=0 izz:=1">
		<link name="wheel_${suffix}">
			<visual>
				<origin xyz="0 0 0" rpy="${-reflect*pi/2} 0 0"/>
				<geometry>
					<!--mesh filename="package://innomech/meshes/wheel_left_link2.stl" scale="0.01 0.01 0.01"/-->
					<mesh filename="${mesh_path}" scale="0.01 0.01 0.01"/>
				</geometry>
				<material name="${color}"/>
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="${-reflect*pi/2} 0 0"/>
				<geometry>
					<cylinder radius="0.057" length="0.025"/>
				</geometry>
				<surface>
					<friction>
						<ode>
							<kp>1000000</kp>
							<kd>1</kd>
							<mu>0.5</mu>
							<mu2>0.5</mu2>
						</ode>
					</friction>
				</surface>
			</collision>
			<xacro:default_inertial mass="${mass}" 
				ixx="${wheel_mass*(3*wheel_radius*wheel_radius*wheel_radius+wheel_thickness*wheel_thickness)/12}" 
				iyy="${wheel_mass*(3*wheel_radius*wheel_radius*wheel_radius+wheel_thickness*wheel_thickness)/12}" 
				izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
		</link>	

		<!-- Joint-->
		<joint name="wheel_${suffix}_joint" type="${joint_type}">
			<parent link="${parent}"/>
			<child link="wheel_${suffix}"/>
			<origin xyz="-0.04 ${reflect*0.13} 0.05" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
			<!--limit velocity="4.8" effort="1" lower="${-pi}" upper="${pi}" /-->
		</joint>

		<transmission name="wheel_${suffix}_transmission" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="$wheel_${suffix}_motor">
				<mechanicalReduction>1</mechanicalReduction>
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</actuator>

			<joint name="wheel_${suffix}_joint">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</joint>
		</transmission>
	</xacro:macro>
	<!--Wheel Macro-->

	<!--MACROS END-->

	<!-- Base_link -->
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://innomech/meshes/base_link2.stl" scale="0.01 0.01 0.01"/>
			</geometry>
			<material name="white"/>
		</visual>

		<collision>
			<origin xyz="0 0 0.1" rpy="0 0 0"/>
			<geometry>
				<box size="${base_height} ${base_width} ${base_depth}" />
			</geometry>
		</collision>

		<xacro:default_inertial mass="${base_mass}" 
			ixx="${base_mass*(base_width*base_width+base_depth*base_depth)/12}" 
			iyy="${base_mass*(base_height*base_height+base_depth*base_depth)/12}"  
			izz="${base_mass*(base_width*base_width+base_height*base_height)/24}" />
	</link>

	<!-- Point Wheel 1-->
	<link name="point_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<sphere radius="0.005"/>
			</geometry>
			<material name="white"/>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<sphere radius="0.005"/>
			</geometry>
			<surface>
				<friction>
					<ode>						
						<mu>0.00001</mu>						
						<mu2>0.8</mu2>						
						<kp  value="10000000.0" />
						<kd  value="1.0" />

					</ode>
				</friction>
			</surface>
		</collision>
		<xacro:default_inertial mass="0.005" 
			ixx="${ball_wheel_radius*ball_wheel_radius*0.005*2/5}"
			iyy="${ball_wheel_radius*ball_wheel_radius*0.005*2/5}" 
			izz="${ball_wheel_radius*ball_wheel_radius*0.005*2/5}"/>
	</link>	

	<joint name="point_wheel_joint" type="continuous">
			<parent link="base_link"/>
			<child link="point_wheel"/>
			<origin xyz="0.08 0.0 -0.0030" rpy="0 0 0"/>
			<axis xyz="1 0 0"/>		
	</joint>	

	<!-- Left Wheel -->
	<xacro:wheel_link suffix="left" parent="base_link" reflect="1" height="1" color="black" mesh_path="package://innomech/meshes/wheel_left_link2.stl" mass="0.240" ixx="0.0002285" ixy="0.0" ixz="0.0" iyy="0.0002285" iyz="0.0" izz="0.000432"/>
	<!-- Left Wheel -->

	<!-- Right Wheel -->
	<xacro:wheel_link suffix="right" parent="base_link" reflect="-1" height="1" color="black" mesh_path="package://innomech/meshes/wheel_left_link2.stl" mass="0.240" ixx="0.0002285" ixy="0.0" ixz="0.0" iyy="0.0002285" iyz="0.0" izz="0.000432"/>
	<!-- Right Wheel -->


	<!--Link0 -->
	<xacro:arm_link suffix="0" parent="base_link" reflect="1" height="0.25" color="orange" mesh_path="package://innomech/meshes/mx-64t2.stl" mass="0.135" joint_type="revolute" lower_limit="${-pi/2}" upper_limit="${pi/2}" axis_x="0" axis_y="0" axis_z="1"
		arm_width_="0.04" arm_height_="0.04" arm_depth_="0.04" motor="1.0" jointInterface="Position"/>
	<!-- Link0 -->

	<!-- Link1 -->
	<xacro:arm_link suffix="1" parent="armLink0" reflect="1" height="0.0" color="red" mesh_path="package://innomech/meshes/linked_mx_64t.stl" mass="0.168" joint_type="revolute" lower_limit="${-pi/4}" upper_limit="${pi/4}" axis_x="0" axis_y="1" axis_z="0" 
		ixx="${arm_mass*(arm_width*arm_width+arm_depth*arm_depth)/12}" 
		iyy="${arm_mass*(arm_height*arm_height+arm_depth*arm_depth)/12}"  
		izz="${arm_mass*(arm_width*arm_width+arm_height*arm_height)/12}"
		arm_width_="${arm_width}" arm_height_="${arm_height}" arm_depth_="${arm_depth}"/>
	<!-- Link1 -->

	<!-- Link2 -->
	<xacro:arm_link suffix="2" parent="armLink1" reflect="1" height="0.12" color="green" mesh_path="package://innomech/meshes/linked_mx_64t.stl" mass="0.168" joint_type="revolute" lower_limit="${-pi/4}" upper_limit="${pi/4}" axis_x="0" axis_y="1" axis_z="0" 	ixx="${arm_mass*(arm_width*arm_width+arm_depth*arm_depth)/12}" 
		iyy="${arm_mass*(arm_height*arm_height+arm_depth*arm_depth)/12}"  
		izz="${arm_mass*(arm_width*arm_width+arm_height*arm_height)/12}"
		arm_width_="${arm_width}" arm_height_="${arm_height}" arm_depth_="${arm_depth}"/>
	<!-- Link2 -->

	<!-- Link3 -->
	<xacro:arm_link suffix="3" parent="armLink2" reflect="1" height="0.12" color="grey" mesh_path="package://innomech/meshes/linked_mx_64t.stl" mass="0.168" joint_type="revolute" lower_limit="${-pi/4}" upper_limit="${pi/4}" axis_x="0" axis_y="1" axis_z="0" 	ixx="${arm_mass*(arm_width*arm_width+arm_depth*arm_depth)/12}" 
		iyy="${arm_mass*(arm_height*arm_height+arm_depth*arm_depth)/12}"  
		izz="${arm_mass*(arm_width*arm_width+arm_height*arm_height)/12}"
		arm_width_="${arm_width}" arm_height_="${arm_height}" arm_depth_="${arm_depth}"/>
	
	<!-- Link3 -->
	





	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/</robotNamespace>
		</plugin>
	</gazebo>

</robot>