# type: "effort_controllers/JointGroupPositionController"
# joints: 
#  - base_link_armLink0_joint
#  - armLink0_armLink1_joint
#  - armLink1_armLink2_joint
#  - armLink2_armLink3_joint

joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_armLink0_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: armLink0_armLink1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: armLink1_armLink2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: armLink2_armLink3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}